<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFbq5COU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFbq5COU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFbq5COU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFbq5COU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFbq5COU\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fbq5COU',
    'container.build_id' => 'acde8517',
    'container.build_time' => 1541948390,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFbq5COU');
