<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO99t2P4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO99t2P4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO99t2P4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO99t2P4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerO99t2P4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'O99t2P4',
    'container.build_id' => 'baac702a',
    'container.build_time' => 1542017037,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO99t2P4');
