<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1ka1Xtx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1ka1Xtx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1ka1Xtx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1ka1Xtx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container1ka1Xtx\srcDevDebugProjectContainer(array(
    'container.build_hash' => '1ka1Xtx',
    'container.build_id' => '701b0f75',
    'container.build_time' => 1541929104,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1ka1Xtx');
